name: ui_anim_page
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  simple_animations: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
      - family: Raleway-BoldItalic
        fonts:
          - asset: assets/fonts/Raleway-BoldItalic.ttf
            style: italic
      - family: Billabong
        fonts:
          - asset: assets/fonts/Billabong.ttf
            weight: 700



